### ISSUE TITLE
Confusion about a line in Routing.md

### ISSUE THREAD

**Issue by devicenull** [CumulusNetworks/docs#1022]
https://github.com/CumulusNetworks/docs/blob/stage/content/cumulus-linux-42/Layer-3/Routing.md

> If the interface is bounced up and down, then the routes are no longer in the route table.

I'm not quite sure what this sentence is trying to say.  Based on the config provided, it looks like this route would be readded after the interface comes back up.

**Comment by plumbis** [comment]
That is super confusing. Let me dig in and we'll get that fixed up.

**Comment by plumbis** [comment]
After following up I don't think I have any idea why that line is in there.

The routing chapter is currently going through a rewrite and we'll make sure that gets cleaned up. (CC @cumulusAnia )

Closing this out as it will be fixed in the rewrite in the next few weeks.
