### ISSUE TITLE
Tacacs+ Page not accessible

### ISSUE THREAD

**Issue by bastischubert** [CumulusNetworks/docs#1038]
Hi there,

when using the Online Documentation at https://docs.cumulusnetworks.com/cumulus-linux-42/System-Configuration/Authentication-Authorization-and-Accounting/ (or any other page on that Level that has direct Links) you cannot access the "TACACS+" documentation. 

Seems like the Link "https://docs.cumulusnetworks.com/cumulus-linux-42/System-Configuration/Authentication-Authorization-and-Accounting/TACACS+/" is br0ken/invalid.

**Comment by plumbis** [comment]
Interesting, this seems to be a problem with the special `+` character in the URL. 

You can access the doc here:
https://docs.cumulusnetworks.com/cumulus-linux-42/System-Configuration/Authentication-Authorization-and-Accounting/TACACS%2B/

It appears this was a recent change in the underlying hosting platform. We will get the link fixed.

**Comment by plumbis** [comment]
The links have been fixed, thanks again!
