### ISSUE TITLE
Cumulus Linux 4.2: User Guide PDF: missing index

### ISSUE THREAD

**Issue by tryfail** [CumulusNetworks/docs#1060]
In the PDF for Cumulus 4.2, there is no index present. The PDF currently contains over 2000 pages and is available at [https://docs.cumulusnetworks.com/cumulus-linux-42/](https://docs.cumulusnetworks.com/cumulus-linux-42/)

This seems to be a regression as compared to the PDF for Cumulus Linux 3.7, which has a very usable index. Available at [https://docs.cumulusnetworks.com/cumulus-linux-37/](https://docs.cumulusnetworks.com/cumulus-linux-37/)

**Comment by plumbis** [comment]
I will see what we can do to generate the index for the PDFs, but if your PDF reader has the ability to see the embedded PDF table of contents you should have something similar. See this screenshot from Firefox with the 4.2 PDF.
![Screen Shot 2020-11-06 at 10 08 55 AM](https://user-images.githubusercontent.com/10537576/98381638-27903c00-2018-11eb-8fdb-bfb2e608cbd2.png)
