### ISSUE TITLE
Cumulus Linux 4.2: User Guide PDF: broken links

### ISSUE THREAD

**Issue by tryfail** [CumulusNetworks/docs#1061]
The User Guide PDF for version 4.2 contains a lot of similarly broken links. The PDF is available at [https://docs.cumulusnetworks.com/cumulus-linux-42/](https://docs.cumulusnetworks.com/cumulus-linux-42/)

**Example**
All links with text 'Management VRF' point neither to the respective PDF section nor the respective online manual section. Instead, the links point to something like https://stage.*.amplifyapp.com/cumulus-linux-42/Layer-3/Management-VRF/ , where the '*' is some (not sure if variable) alpha-numeric id . Seems to be the result of the amplify.yaml configuration file.

I do not have any proposed solution, because I am not familiar with the build process.

**Comment by plumbis** [comment]
Thanks for the report.

The way we generate PDFs is a bit convoluted and involves a hidden page that combines all of the doc pages, then a javascript function _should_ rewrite all of the links to be relative to that page _then_ that page is turned into a PDF. 

Seems like the javascript part is busted. I'll investigate and let you know when I have a fix.
