### ISSUE TITLE
Example configuration for Voice VLAN did not match with the image

### ISSUE THREAD

**Issue by mape2k** [CumulusNetworks/docs#1089]
* Image has only swp1/swp2
* Vlans on image does not match vlans in example configuration

https://docs.cumulusnetworks.com/cumulus-linux-42/Layer-2/Link-Layer-Discovery-Protocol/Voice-VLAN/#example-configuration

**Comment by plumbis** [comment]
@cumulusAnia I think the easiest fix here is to update the graphic, can you take this one?

**Comment by plumbis** [comment]
@cumulusAnia has pushed a change to the image and config example to make them accurate with commit 6df5c1fd9b96093e3e3db6366689c5951055625d. Thanks Ania!
