### ISSUE TITLE
PDF version of user guide missing

### ISSUE THREAD

**Issue by akt68** [CumulusNetworks/docs#1221]
The link to the pdf version of the user guide (https://docs.nvidia.com/cumulus-linux-43/cumulus-linux-43.pdf) redirects immediately to https://docs.nvidia.com/. How can I download a pdf version of the dokumentation?
The same issue is true for version 4.0, 4.1, 4.3 and 3.7.12 ESR (https://docs.nvidia.com/cumulus-linux-37/cumulus-linux-37.pdf).

**Comment by plumbis** [comment]
Due to the domain transition to docs.nvidia we have a few outstanding backend problems that has caused us to not publish PDFs for the time being. If you email me at my github username @nvidia.com I can provide you PDFs for the versions you are looking for.

-Pete

**Comment by plumbis** [comment]
Discussed with the user offline and provided PDFs via email
