### ISSUE TITLE
Local build procedure doesn't work.

### ISSUE THREAD

**Issue by networkop** [CumulusNetworks/docs#1384]
I'm following [this  procedure](https://github.com/CumulusNetworks/docs#installing-the-documentation-and-running-the-local-server) but can't get the server running.  It hangs for a long time and then fails:
```
~/docs stage !1 ?1 ❯ ./hugo server -v
INFO 2021/07/26 20:28:29 Using config file:
Start building sites …
INFO 2021/07/26 20:28:29 syncing static files to /
Built in 97810 ms
Error: Error building site: TOCSS: failed to transform "book.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.
~/docs stage !1 ?1 ❯ ./hugo version                                                                                     ✘ 255 1m 38s
hugo v0.82.0-9D960784 linux/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
```

**Comment by desertmonkey** [comment]
Thanks for pitching in @networkop; this is always very much appreciated.

Do you remember when you installed Hugo 0.82 if you installed an extended release? It would be something like https://github.com/gohugoio/hugo/releases/download/v0.82.0/hugo_extended_0.82.0_macOS-ARM64.tar.gz

**Comment by networkop** [comment]
🤦  extended, of course. should've read the docs more closely. thanks for quick response.
