### ISSUE TITLE
Doc Fix: Invalid Option for vm-backuprestore.sh Script

### ISSUE THREAD

**Issue by mtbutler07** [CumulusNetworks/docs#2213]
The [documentation for backing up NetQ 4.5.0 or later ](https://docs.nvidia.com/networking-ethernet-software/cumulus-netq-47/Installation-Management/Backup-and-Restore-NetQ/#back-up-netq-450-or-later)references an option that is invalid.

The command `sudo /usr/sbin/vm-backuprestore.sh --backup --start-pods` 
needs to be updated to `sudo /usr/sbin/vm-backuprestore.sh --backup --start_pods`

Specifically the underscore instead of hyphen in `--start_pods`

**Comment by rachel-netq** [comment]
Thank you, Marcus! We’ve [updated that page](https://docs.nvidia.com/networking-ethernet-software/cumulus-netq-47/Installation-Management/Backup-and-Restore-NetQ/#back-up-netq-450-or-later) with the corrected script.
