### ISSUE TITLE
Invalid NV Set commands

### ISSUE THREAD

**Issue by mtbutler07** [CumulusNetworks/docs#2216]
The following commands are invalid in this document:
https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-55/System-Configuration/Authentication-Authorization-and-Accounting/SSH-for-Remote-Access/#nvue-managed-user

```bash
cumulus@leaf01:~$ nv set user admin2 ssh authorized-key prod_key key 1234
cumulus@leaf01:~$ nv set user admin2 ssh authorized-key prod_key type ssh-rsa
cumulus@leaf01:~$ nv config apply
```

Probably just needs to be updated to `nv set system aaa user ...`

Additionally, it would be nice to see a more realistic example of this command as adding user accounts is a very common task.

**Comment by cumulusAnia** [comment]
fixed incorrect commands and provided a longer key example
