### ISSUE TITLE
Missing Documentation/Example for "nv show system config apply overwrite"

### ISSUE THREAD

**Issue by mtbutler07** [CumulusNetworks/docs#2221]
https://docs.nvidia.com/networking-ethernet-software/nvue-reference/Show-Commands/System-Config/

This page seems to be missing documentation and an example for `overwrite: all`.

```bash
cumulus@switch:mgmt:~$ nv show system config apply
ignore: {}
overwrite: all

```

**Comment by cumulusAnia** [comment]
added description of ignore and overwrite
